In [1]:
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt
import os

In [14]:
#charger élections
df_ele = pd.read_excel("data/raw/elections_legislatives.xlsx")

#charger élections au 1er tour
df_ele1 = pd.read_excel("data/raw/elections_t1_legislatives.xlsx")

#charger population
df_pop = pd.read_excel("data/raw/Population_communes.xlsx", skiprows = 7, sheet_name = "Communes")

#charger degré de densité de population en 2022
df_densite = pd.read_excel("data/raw/Degre_densite.xlsx", skiprows = 4)

#Aperçu des données
print("Degré de densité:")
display(df_densite.head())

print("Elections:")
display(df_ele.head())

print("Elections 1er tour:")
display(df_ele1.head())

print("Population:")
display(df_pop.head())

Degré de densité:

,CODGEO,LIBGEO,DENS,LIBDENS,PMUN22,P1,P2,P3,DENS_AAV,LIBDENS_AAV,DENS7,LIBDENS7
0,01001,L'Abergement-Clémenciat,3,Rural,859,0.0,0.000000,100.000000,4,Rural non périurbain,6,Rural à habitat dispersé
1,01002,L'Abergement-de-Varey,3,Rural,273,0.0,0.000000,100.000000,4,Rural non périurbain,6,Rural à habitat dispersé
2,01004,Ambérieu-en-Bugey,2,Urbain intermédiaire,15554,0.0,96.933762,3.066238,2,Urbain intermédiaire,2,Centres urbains intermédiaires
3,01005,Ambérieux-en-Dombes,3,Rural,1917,0.0,0.000000,100.000000,3,Rural périurbain,5,Bourgs ruraux
4,01006,Ambléon,3,Rural,114,0.0,0.000000,100.000000,4,Rural non périurbain,6,Rural à habitat dispersé

Elections:

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,...,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196
0,01,Ain,1,1ère circonscription,16,Arbigny,Complet,327,154,47.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01,Ain,1,1ère circonscription,24,Attignat,Complet,2454,1281,52.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01,Ain,1,1ère circonscription,29,Beaupont,Complet,446,224,50.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,Ain,1,1ère circonscription,38,Bény,Complet,604,306,50.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,Ain,1,1ère circonscription,40,Béréziat,Complet,362,179,49.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Elections 1er tour:

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Etat saisie,Inscrits,Abstentions,% Abs/Ins,...,Unnamed: 187,Unnamed: 188,Unnamed: 189,Unnamed: 190,Unnamed: 191,Unnamed: 192,Unnamed: 193,Unnamed: 194,Unnamed: 195,Unnamed: 196
0,01,Ain,1,1ère circonscription,16,Arbigny,Complet,327,154,47.09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01,Ain,1,1ère circonscription,24,Attignat,Complet,2454,1281,52.20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01,Ain,1,1ère circonscription,29,Beaupont,Complet,446,224,50.22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,Ain,1,1ère circonscription,38,Bény,Complet,604,306,50.66,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,Ain,1,1ère circonscription,40,Béréziat,Complet,362,179,49.45,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Population:

,Code région,Nom de la région,Code département,Code arrondissement,Code canton,Code commune,Nom de la commune,Population municipale,Population comptée à part,Population totale
0,84,Auvergne-Rhône-Alpes,01,2.0,08,1,L' Abergement-Clémenciat,860,16,876
1,84,Auvergne-Rhône-Alpes,01,1.0,01,2,L' Abergement-de-Varey,270,6,276
2,84,Auvergne-Rhône-Alpes,01,1.0,01,4,Ambérieu-en-Bugey,15934,405,16339
3,84,Auvergne-Rhône-Alpes,01,2.0,22,5,Ambérieux-en-Dombes,1906,24,1930
4,84,Auvergne-Rhône-Alpes,01,1.0,04,6,Ambléon,115,0,115

In [17]:
print(df_densite.columns)
print(df_ele.columns)
print(df_ele.columns)
print(df_pop.columns)

Index(['CODGEO', 'LIBGEO', 'DENS', 'LIBDENS', 'PMUN22', 'P1', 'P2', 'P3',
       'DENS_AAV', 'LIBDENS_AAV', 'DENS7', 'LIBDENS7'],
      dtype='object')
Index(['Code du département', 'Libellé du département',
       'Code de la circonscription', 'Libellé de la circonscription',
       'Code de la commune', 'Libellé de la commune', 'Etat saisie',
       'Inscrits', 'Abstentions', '% Abs/Ins',
       ...
       'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190',
       'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194',
       'Unnamed: 195', 'Unnamed: 196'],
      dtype='object', length=197)
Index(['Code du département', 'Libellé du département',
       'Code de la circonscription', 'Libellé de la circonscription',
       'Code de la commune', 'Libellé de la commune', 'Etat saisie',
       'Inscrits', 'Abstentions', '% Abs/Ins',
       ...
       'Unnamed: 187', 'Unnamed: 188', 'Unnamed: 189', 'Unnamed: 190',
       'Unnamed: 191', 'Unnamed: 192', 'Unnamed: 193', 'Unnamed: 194',
       'Unnamed: 195', 'Unnamed: 196'],
      dtype='object', length=197)
Index(['Code région', 'Nom de la région', 'Code département',
       'Code arrondissement', 'Code canton', 'Code commune',
       'Nom de la commune', 'Population municipale',
       'Population comptée à part', 'Population totale'],
      dtype='object')

In [18]:
df_densite.isna.sum()

AttributeError: 'function' object has no attribute 'sum'